sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t equalessdev/hello-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true 5f792c430b10 npm run test